name: Release Plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Building the plugin
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache
          restore-keys: cache

      - name: Compile android plugins
        run: |
          ./scripts/android/release.sh
          ls -l .release/android

      - name: Compile ios plugins
        run: |
          ./scripts/ios/release.sh
          ls -l .release/ios

      - uses: actions/upload-artifact@v2
        with:
          name: plugins
          path: .release/*/*.zip
          retention-days: 4
          if-no-files-found: error