name: Release Plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Building the plugin
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache
          restore-keys: cache

      - name: Compile android plugins
        run: |
          ./scripts/android/release.sh
          ls -l .release/android

      - name: Compile ios plugins
        run: |
          ./scripts/ios/release.sh
          ls -l .release/ios

      - uses: actions/upload-artifact@v2
        with:
          name: plugins
          path: .release/*/*.zip
          retention-days: 4
          if-no-files-found: error